### ISSUE TITLE
Create server from scratch

### ISSUE THREAD

**Issue by bjsawyer** [excellalabs/excella-central#43]
www.github.com/excellalabs/excella-central-server

## Tasks:

- [x] Create new project via LoopBack CLI 
- [x] Create Profile model
- [x] Create Account model (which extends LoopBack's "User" model)
- [ ] Connect MongoDB instance as datasource
- [ ] Setup Travis CI pipeline for builds & deployment
- [ ] Deploy server to labs.excella.com (in place of the existing server)
